# Generated by Django 5.0.6 on 2024-06-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_chat_delete_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('username', models.TextField()),
                ('language_code', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
