# Generated by Django 5.0.6 on 2024-06-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_delete_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='external_id',
        ),
    ]
