# Generated by Django 5.0.6 on 2024-06-15 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_user_botuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('image_message_id', models.BigIntegerField(null=True)),
                ('content_message_id', models.BigIntegerField(null=True)),
                ('results', models.JSONField()),
                ('results_count', models.BigIntegerField()),
                ('status', models.TextField()),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.botuser')),
            ],
        ),
    ]
