# Generated by Django 5.0.6 on 2024-06-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_search_bot_user_search_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='seasons_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='selected_season',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='selected_show_tvdb_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='selected_show_type',
            field=models.BigIntegerField(null=True),
        ),
    ]
