# Generated by Django 5.0.6 on 2024-06-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_search_seasons_data_search_selected_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='selected_show_name',
            field=models.TextField(null=True),
        ),
    ]
