# Generated by Django 5.0.6 on 2024-06-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_search_selected_show_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='selected_show_name',
            new_name='selected_show_title',
        ),
    ]
