# Generated by Django 5.0.6 on 2024-06-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_selected_show_type_search_selected_show_tvdb_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='selected_show_tvdb_type',
            field=models.TextField(null=True),
        ),
    ]
