# Generated by Django 5.0.6 on 2024-06-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_search_selected_show_tvdb_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='found_releases',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='selected_release_guid',
            field=models.TextField(null=True),
        ),
    ]
