# Generated by Django 5.0.6 on 2024-06-19 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_search_found_releases_search_selected_release_guid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SonarrDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prowlarr_results', models.JSONField()),
                ('prowlarr_indexer', models.BigIntegerField(null=True)),
                ('prowlarr_guid', models.TextField(null=True)),
                ('episode_count', models.IntegerField(null=True)),
                ('files', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SonarrSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.BigIntegerField()),
                ('path', models.FilePathField()),
                ('tvdb_id', models.BigIntegerField()),
                ('tvdb_type', models.TextField()),
                ('tvdb_year', models.TextField()),
                ('tvdb_country', models.TextField()),
                ('tvdb_title', models.TextField()),
                ('tvdb_image_url', models.TextField()),
                ('tvdb_overview', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SonarrMonitoredSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.BigIntegerField()),
                ('season_number', models.IntegerField()),
                ('episode_file_count', models.IntegerField()),
                ('episode_count', models.IntegerField()),
                ('total_episodes_count', models.IntegerField()),
                ('previous_airing', models.DateTimeField(null=True)),
                ('current_download', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sonarrdownload')),
            ],
        ),
        migrations.AddField(
            model_name='sonarrdownload',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sonarrmonitoredseason'),
        ),
    ]
