# Generated by Django 5.0.6 on 2024-06-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_sonarrdownload_sonarrseries_sonarrmonitoredseason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonarrseries',
            name='tvdb_country',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sonarrseries',
            name='tvdb_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sonarrseries',
            name='tvdb_image_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sonarrseries',
            name='tvdb_overview',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sonarrseries',
            name='tvdb_title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sonarrseries',
            name='tvdb_type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sonarrseries',
            name='tvdb_year',
            field=models.TextField(null=True),
        ),
    ]
