# Generated by Django 5.0.6 on 2024-06-20 17:19

import bot.dependencies.prowlarr
import django.core.serializers.json
import django.db.models.deletion
import django_pydantic_field.compat.django
import django_pydantic_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_sonarrdownload_prowlarr_results_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sonarrmonitoredseason',
            name='series_id',
        ),
        migrations.RemoveField(
            model_name='sonarrreleaseselect',
            name='series',
        ),
        migrations.AddField(
            model_name='sonarrmonitoredseason',
            name='current_select',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sonarrreleaseselect'),
        ),
        migrations.AddField(
            model_name='sonarrreleaseselect',
            name='chat_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sonarrreleaseselect',
            name='image_message_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sonarrreleaseselect',
            name='keyboard_message_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sonarrreleaseselect',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.sonarrmonitoredseason'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sonarrreleaseselect',
            name='prowlarr_results',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (bot.dependencies.prowlarr.ProwlarrRelease,))),
        ),
        migrations.AlterField(
            model_name='sonarrseries',
            name='series_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
