# Generated by Django 5.0.6 on 2024-06-20 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_sonarrmonitoredseason_series_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonarrmonitoredseason',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seasons', to='app.sonarrseries', to_field='series_id'),
            preserve_default=False,
        ),
    ]
