# Generated by Django 5.0.6 on 2024-06-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_sonarrmonitoredseason_series'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sonarrreleaseselect',
            old_name='keyboard_message_id',
            new_name='description_message_id',
        ),
        migrations.AddField(
            model_name='sonarrreleaseselect',
            name='select_message_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
