# Generated by Django 5.0.6 on 2024-06-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_keyboard_message_id_sonarrreleaseselect_description_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonarrseries',
            name='tvdb_title_en',
            field=models.TextField(null=True),
        ),
    ]
