# Generated by Django 5.0.6 on 2024-06-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_sonarrseries_tvdb_title_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sonarrreleaseselect',
            name='description_message_id',
        ),
        migrations.RemoveField(
            model_name='sonarrreleaseselect',
            name='image_message_id',
        ),
    ]
