# Generated by Django 5.0.6 on 2024-06-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_remove_sonarrreleaseselect_description_message_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sonarrdownload",
            name="torrent",
            field=models.FileField(default=1, upload_to=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sonarrreleaseselect",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sonarrdownload",
            name="episode_count",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sonarrdownload",
            name="files",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sonarrdownload",
            name="prowlarr_guid",
            field=models.TextField(default="1"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sonarrdownload",
            name="prowlarr_indexer",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
