# Generated by Django 5.0.6 on 2024-06-22 20:01

import django.core.serializers.json
import django_pydantic_field.fields
from django.db import migrations, models

import bot.dependencies.prowlarr


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0023_sonarrdownload_torrent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sonarrdownload",
            name="files",
        ),
        migrations.RemoveField(
            model_name="sonarrdownload",
            name="torrent",
        ),
        migrations.AddField(
            model_name="sonarrdownload",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sonarrdownload",
            name="prowlarr_torrent_data",
            field=models.BinaryField(default=b""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sonarrdownload",
            name="prowlarr_torrent_meta",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                schema=bot.dependencies.prowlarr.ProwlarrTorrentMeta,
            ),
            preserve_default=False,
        ),
    ]
