# Generated by Django 5.0.6 on 2024-06-22 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_sonarrdownload_files_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sonarrdownload',
            old_name='prowlarr_indexer',
            new_name='prowlarr_indexer_id',
        ),
    ]
