version: '3.8'

services:
  releasarr:
    build: 
      context: .
    restart: always
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./logs/backend:/app/logs
    env_file:
      - .env
    environment:
      - ENABLE_TASK_SCHEDULER=1
    ports:
      - 8050:80