version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    restart: always
    volumes:
      - ./db.sqlite3:/app/db.sqlite3

  sqlitebrowser:
    image: lscr.io/linuxserver/sqlitebrowser:latest
    container_name: sqlitebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped