version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./logs/backend:/app/logs
    env_file:
      - .env
    environment:
      - ENABLE_TASK_SCHEDULER=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      - REACT_APP_BACKEND_URL=http://code-vm.lan:8050

  nginx:
    image: nginx:latest
    ports:
      - "8050:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
