version: '3.8'

services:
  releasarr:
    build: 
      context: .
    restart: always
    volumes:
      - ./backend/releasarr.db:/app/releasarr.db
      - ./backend/logs:/app/logs
    env_file:
      - ./backend/.env
    ports:
      - 8050:80