version: '3.8'

services:
  releasarr:
    build: 
      context: .
    restart: always
    volumes:
      - ./backend_new/releasarr.db:/app/releasarr.db
      - ./backend_new/logs:/app/logs
    env_file:
      - ./backend_new/.env
    ports:
      - 8050:80