version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    restart: always
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./logs/backend:/app/logs
