version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    restart: always
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./logs/backend:/app/logs
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8011:80"
    restart: always
    environment:
      - REACT_APP_BACKEND_URL=http://code-vm.lan:8001
