version: '3.8'

services:
  releasarr:
    build: 
      context: .
    restart: always
    volumes:
      - ./backend_v2/releasarr.db:/app/releasarr.db
      - ./backend_v2/logs:/app/logs
    env_file:
      - ./backend_v2/.env
    ports:
      - 8050:80