version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    restart: always
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./logs:/app/logs
