name: build-and-push

on: [push, pull_request]

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: docker

    container:
      image: docker:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    
    steps:
      - name: Install Node.js
        run: |
          apk add --no-cache nodejs npm
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      # - name: Login to Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{ secrets.REGISTRY_URL }}
      #     username: ${{ secrets.REGISTRY_USERNAME }}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,format=short
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:buildcache,mode=max