name: build-and-push

on: [push, pull_request]

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Login to Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{ vars.REGISTRY_URL }}
      #     username: ${{ vars.REGISTRY_USERNAME }}
      #     password: ${{ vars.REGISTRY_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.REGISTRY_URL }}/${{ vars.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,format=short
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ vars.REGISTRY_URL }}/${{ vars.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ vars.REGISTRY_URL }}/${{ vars.IMAGE_NAME }}:buildcache,mode=max