name: lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Ruff Linting
    runs-on: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Ruff checks
        uses: docker://python:3.12-slim
        with:
          entrypoint: /bin/bash
          args: |-
            -c "
            cd backend
            pip install uv
            uv venv     
            echo 'Running Ruff linting checks...'
            uv run ruff check ./src
            echo 'Running Ruff format checks...'
            uv run ruff format --check ./src
            "

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.REGISTRY_URL }}/${{ vars.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ vars.REGISTRY_URL }}/${{ vars.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ vars.REGISTRY_URL }}/${{ vars.IMAGE_NAME }}:buildcache,mode=max

  deploy:
    name: Deploy
    runs-on: ubuntu
    needs: build-and-push
    steps:
      - name: SSH and update Docker Compose
        uses: https://github.com/appleboy/ssh-action@master
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ vars.DEPLOY_PORT || 22 }}
          script: |
            cd ${{ vars.DEPLOY_DIRECTORY }}
            docker compose pull
            docker compose up -d
