name: lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Ruff Linting
    runs-on: ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv and dependencies
        run: |
          pip install uv
          uv venv

      - name: Run Ruff linting
        working-directory: backend
        run: uv run ruff check ./src

      - name: Run Ruff formatting
        working-directory: backend
        run: uv run ruff format --check ./src

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.REGISTRY_URL }}/${{ vars.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ vars.REGISTRY_URL }}/${{ vars.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ vars.REGISTRY_URL }}/${{ vars.IMAGE_NAME }}:buildcache,mode=max

  deploy:
    name: Deploy
    runs-on: ubuntu
    needs: build-and-push
    steps:
      - name: SSH and update Docker Compose
        uses: https://github.com/appleboy/ssh-action@master
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ vars.DEPLOY_PORT || 22 }}
          script: |
            cd ${{ vars.DEPLOY_DIRECTORY }}
            docker compose pull
            docker compose up -d
