apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetch-updates-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: fetch-updates-worker
        image: registry.koreetz.synology.me/media_manager_bot:2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
          - name: media
            mountPath: /Media
        command: ["poetry", "run", "python", "-m", "commands.run_fetch_updates_worker"]
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: "admin.config.settings"
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
