"""empty message

Revision ID: 240b8bb36cb7
Revises: 866ed1fe4bed
Create Date: 2024-09-08 20:02:31.610289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '240b8bb36cb7'
down_revision: Union[str, None] = '866ed1fe4bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('last_imported_files_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'last_imported_files_hash')
    # ### end Alembic commands ###
