"""empty message

Revision ID: 866ed1fe4bed
Revises: 8c90e8aaccb1
Create Date: 2024-09-07 11:32:05.757942

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "866ed1fe4bed"
down_revision: Union[str, None] = "8c90e8aaccb1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "release",
        sa.Column("prowlarr_guid", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_column("release", "search_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("release", sa.Column("search_name", sa.VARCHAR(), nullable=False))
    op.drop_column("release", "prowlarr_guid")
    # ### end Alembic commands ###
