"""empty message

Revision ID: 8c90e8aaccb1
Revises: 
Create Date: 2024-09-04 18:26:23.473417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8c90e8aaccb1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sonarr_id', sa.Integer(), nullable=True),
    sa.Column('sonarr_data_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tvdb_data_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_missing', sa.Boolean(), nullable=False),
    sa.Column('missing_seasons', sa.JSON(), nullable=False),
    sa.Column('prowlarr_search', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prowlarr_data_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sonarr_id')
    )
    op.create_index(op.f('ix_show_is_missing'), 'show', ['is_missing'], unique=False)
    op.create_table('release',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('search', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('search_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('qbittorrent_guid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qbittorrent_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('releasefilematching',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['release_name'], ['release.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('releasefilematching')
    op.drop_table('release')
    op.drop_index(op.f('ix_show_is_missing'), table_name='show')
    op.drop_table('show')
    # ### end Alembic commands ###
