"""empty message

Revision ID: 242216254861
Revises: 
Create Date: 2025-05-08 07:44:27.510947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '242216254861'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prowlarr_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_string', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('info_url', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('torrents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tvdb_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tvdb_series_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tvdb_series_tvdb_series_id'), 'tvdb_series', ['tvdb_series_id'], unique=True)
    op.create_table('sonarr_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sonarr_series_id', sa.Integer(), nullable=False),
    sa.Column('tvdb_series_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), nullable=False),
    sa.Column('is_missing', sa.Boolean(), nullable=False),
    sa.Column('episodes', sa.JSON(), nullable=False),
    sa.Column('prowlarr_manual_search_string', sa.String(), nullable=True),
    sa.Column('prowlarr_release_id', sa.Integer(), nullable=True),
    sa.Column('torrent_id', sa.Integer(), nullable=True),
    sa.Column('torrent_files_matching', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_imported_torrent_guid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['prowlarr_release_id'], ['prowlarr_releases.id'], ),
    sa.ForeignKeyConstraint(['torrent_id'], ['torrents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sonarr_requests_sonarr_series_id'), 'sonarr_requests', ['sonarr_series_id'], unique=False)
    op.create_index(op.f('ix_sonarr_requests_tvdb_series_id'), 'sonarr_requests', ['tvdb_series_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sonarr_requests_tvdb_series_id'), table_name='sonarr_requests')
    op.drop_index(op.f('ix_sonarr_requests_sonarr_series_id'), table_name='sonarr_requests')
    op.drop_table('sonarr_requests')
    op.drop_index(op.f('ix_tvdb_series_tvdb_series_id'), table_name='tvdb_series')
    op.drop_table('tvdb_series')
    op.drop_table('torrents')
    op.drop_table('prowlarr_releases')
    # ### end Alembic commands ###
