"""create core tables

Revision ID: c2412e7b4945
Revises: None
Create Date: 2025-09-25 11:40:05.044426

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2412e7b4945'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('media_type', sa.Enum('movie', 'series', name='media_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'searching', 'downloading', 'completed', 'failed', name='media_request_status'), server_default='pending', nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_url', sa.String(length=512), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=False),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=64), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('total_episodes', sa.Integer(), nullable=True),
    sa.Column('series_title', sa.String(length=255), nullable=True),
    sa.Column('series_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(media_type = 'movie' AND season_number IS NULL AND total_episodes IS NULL) OR media_type = 'series'", name='ck_media_requests_movie_series_fields'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('releases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('info_hash', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'downloading', 'seeding', 'completed', 'failed', name='release_status'), server_default='pending', nullable=False),
    sa.Column('progress', sa.Float(), server_default='0', nullable=False),
    sa.Column('download_speed', sa.Float(), server_default='0', nullable=False),
    sa.Column('upload_speed', sa.Float(), server_default='0', nullable=False),
    sa.Column('seeders', sa.Integer(), server_default='0', nullable=False),
    sa.Column('leechers', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ratio', sa.Float(), server_default='0', nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('torrent_source', sa.String(length=255), nullable=True),
    sa.Column('quality', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('release_files',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('release_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('mapping_type', sa.Enum('movie', 'series', name='file_mapping_media_type'), nullable=True),
    sa.Column('mapped_request_id', sa.String(length=64), nullable=True),
    sa.Column('mapped_request_title', sa.String(length=255), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('episode', sa.Integer(), nullable=True),
    sa.CheckConstraint("(mapping_type != 'series') OR (season IS NOT NULL AND episode IS NOT NULL)", name='ck_release_files_series_mapping'),
    sa.ForeignKeyConstraint(['mapped_request_id'], ['media_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('release_request_links',
    sa.Column('release_id', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['media_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('release_id', 'request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('release_request_links')
    op.drop_table('release_files')
    op.drop_table('releases')
    op.drop_table('media_requests')
    # ### end Alembic commands ###
