"""add release export fields

Revision ID: 5a168e8321ab
Revises: 9b51f749a7a1
Create Date: 2026-01-23 22:14:07.183187

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a168e8321ab'
down_revision = '9b51f749a7a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('last_exported_info_hash', sa.String(length=128), nullable=True))
    op.add_column('releases', sa.Column('export_failures_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('releases', 'export_failures_count')
    op.drop_column('releases', 'last_exported_info_hash')
    # ### end Alembic commands ###
