"""empty message

Revision ID: 0f993b96ef40
Revises: 240b8bb36cb7
Create Date: 2024-09-12 12:36:10.595018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0f993b96ef40'
down_revision: Union[str, None] = '240b8bb36cb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('prowlarr_data_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'prowlarr_data_raw')
    # ### end Alembic commands ###
