"""empty message

Revision ID: 386ad2a72cb3
Revises: fe212b0a1c9f
Create Date: 2024-09-23 19:22:04.755141

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "386ad2a72cb3"
down_revision: Union[str, None] = "fe212b0a1c9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "release",
        sa.Column(
            "export_failures_count", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("release", "export_failures_count")
    # ### end Alembic commands ###
